# Generated by Django 4.2.6 on 2023-11-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='doctor',
            field=models.IntegerField(default=0),
        ),
    ]
