# Generated by Django 4.2.6 on 2023-11-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointments_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='doctor',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
