# Generated by Django 4.2.6 on 2023-11-16 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_bookings_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
