# Generated by Django 4.2.6 on 2023-11-16 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_cancel_alter_booking_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelwhen',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
