# Generated by Django 4.2.6 on 2023-11-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_appointments_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='doctor',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
