# Generated by Django 4.2.6 on 2023-11-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_cancelwhen'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
