# Generated by Django 4.2.6 on 2023-11-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_appointments_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='doctor',
            field=models.IntegerField(default=0),
        ),
    ]
