# Generated by Django 4.2.6 on 2023-11-16 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.BooleanField(default=datetime.datetime.now, null=True),
        ),
    ]
