# Generated by Django 4.2.6 on 2023-11-23 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_appointments_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demonstration',
        ),
    ]
