# Generated by Django 4.2.6 on 2023-11-18 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demonstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_guest', models.CharField(max_length=255)),
                ('demo_date', models.DateTimeField(default=datetime.datetime.now)),
                ('demo_time', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
