# Generated by Django 4.2.6 on 2023-11-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_delete_demonstration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='calendarinstance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='calendarinstance',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='CalendarInstance',
        ),
    ]
