# Generated by Django 4.2.6 on 2023-11-18 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_demonstration'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstration',
            name='demo_email',
            field=models.EmailField(default='hello@bridgemedia.ie', max_length=255),
        ),
        migrations.AddField(
            model_name='demonstration',
            name='demo_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='demonstration',
            name='demo_guest',
            field=models.CharField(default='Guest Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='demonstration',
            name='demo_time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
