# Generated by Django 4.2.6 on 2023-11-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_demonstration_demo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstration',
            name='demo_time',
            field=models.CharField(choices=[('11AM', '11AM'), ('2PM', '2PM'), ('7PM', '7PM')], default='11AM', max_length=4),
        ),
    ]
