# Generated by Django 4.2.6 on 2023-11-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_demonstration_demo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstration',
            name='demo_date',
            field=models.DateField(),
        ),
    ]
