# Generated by Django 4.2.6 on 2023-11-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_demonstration_demo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meal',
            field=models.CharField(choices=[('NONE', 'NONE'), ('BEEF', 'BEEF'), ('CHICKEN', 'CHICKEN'), ('VEGETARIAN', 'VEGETARIAN')], default='NONE', max_length=99),
        ),
    ]
