# Generated by Django 4.2.6 on 2023-11-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_calendarinstance_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarinstance',
            options={'verbose_name_plural': 'Calendar Entries'},
        ),
        migrations.AlterField(
            model_name='calendarinstance',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.calendar'),
        ),
    ]
