# Generated by Django 4.2.6 on 2023-11-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_calendarinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
