# Generated by Django 4.2.6 on 2023-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_alter_calendarinstance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
