# Generated by Django 4.2.6 on 2023-11-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_alter_calendarinstance_date'),
    ]

    operations = [
    ]
