# Generated by Django 4.2.6 on 2023-11-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auto_20231121_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarinstance',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.calendar'),
        ),
    ]
