# Generated by Django 4.2.6 on 2023-11-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_calendarinstance_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarinstance',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
