# Generated by Django 4.2.6 on 2023-11-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_calendarinstance_booked'),
    ]

    operations = [
    ]
