# Generated by Django 4.2.6 on 2023-11-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_auto_20231121_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarinstance',
            name='start_time',
            field=models.CharField(blank=True, choices=[('9am', '9am'), ('12am', '12am'), ('3pm', '3pm')], default='9am', max_length=10),
        ),
    ]
