# Generated by Django 4.2.6 on 2023-11-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_alter_calendarinstance_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarinstance',
            name='end_time',
        ),
    ]
