# Generated by Django 4.2.6 on 2023-11-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_alter_calendarinstance_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarinstance',
            name='start_time',
            field=models.CharField(blank=True, choices=[('09:00', '09:00'), ('12:00', '12:00'), ('15:00', '15:00')], default='9am', max_length=10),
        ),
    ]
